-- RML Sales Visit v0.10.2 — Login Internal (tanpa Supabase Auth)
-- Jalankan seluruh file ini di Supabase Dashboard > SQL Editor > New Query > Run.
-- File ini menghapus struktur pilot v0.10.0 lalu membuat ulang tabel internal.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Hapus fungsi/tabel pilot lama yang bergantung pada auth.users.
drop function if exists public.lookup_login_email(text) cascade;
drop function if exists public.is_admin() cascade;
drop table if exists public.area_assignments cascade;
drop table if exists public.visits cascade;
drop table if exists public.profiles cascade;

drop table if exists public.app_sessions cascade;
drop table if exists public.app_users cascade;

create table public.app_users (
  id uuid primary key default gen_random_uuid(),
  account_key text unique not null,
  login_name text unique not null,
  display_name text not null,
  phone text unique not null,
  password_hash text not null,
  role text not null check (role in ('admin','sales')),
  must_change_password boolean not null default true,
  active boolean not null default true,
  can_switch_area_freely boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text unique not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now()
);
create index app_sessions_user_idx on public.app_sessions(user_id);
create index app_sessions_expiry_idx on public.app_sessions(expires_at);

create table public.visits (
  id text primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  sales_email text not null default '',
  sales_name text not null default '',
  customer_no text not null default '',
  customer_code text not null default '',
  customer_name text not null default '',
  area text not null default '',
  status text not null default '',
  visit_type text not null default 'Kunjungan Area',
  check_in_at timestamptz,
  check_out_at timestamptz,
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);
create index visits_user_id_idx on public.visits(user_id);
create index visits_check_out_at_idx on public.visits(check_out_at desc);
create index visits_area_idx on public.visits(area);

create table public.area_assignments (
  id bigint generated by default as identity primary key,
  sales_email text not null,
  area text not null,
  created_at timestamptz not null default now(),
  unique(sales_email, area)
);

-- Tidak ada akses tabel langsung dari browser. Semua akses melalui RPC terkontrol.
alter table public.app_users enable row level security;
alter table public.app_sessions enable row level security;
alter table public.visits enable row level security;
alter table public.area_assignments enable row level security;
revoke all on public.app_users, public.app_sessions, public.visits, public.area_assignments from anon, authenticated;

create or replace function public._app_session_user(p_token text)
returns table(user_id uuid, account_key text, role text)
language sql stable security definer set search_path=public
as $$
  select u.id,u.account_key,u.role
  from public.app_sessions s
  join public.app_users u on u.id=s.user_id
  where s.token_hash=encode(extensions.digest(p_token,'sha256'),'hex')
    and s.expires_at>now() and u.active=true
  limit 1;
$$;
revoke all on function public._app_session_user(text) from public, anon, authenticated;

create or replace function public.app_login(p_login_name text,p_password text)
returns table(session_token text,account_key text,display_name text,phone text,role text,must_change_password boolean,expires_at timestamptz)
language plpgsql security definer set search_path=public
as $$
declare v_user public.app_users%rowtype; v_token text; v_exp timestamptz;
begin
  select * into v_user from public.app_users
  where lower(trim(login_name))=lower(trim(p_login_name)) and active=true limit 1;
  if v_user.id is null or v_user.password_hash <> extensions.crypt(p_password,v_user.password_hash) then
    raise exception 'Nama atau password salah';
  end if;
  delete from public.app_sessions s where s.expires_at<=now();
  v_token:=encode(extensions.gen_random_bytes(32),'hex'); v_exp:=now()+interval '30 days';
  insert into public.app_sessions(user_id,token_hash,expires_at)
  values(v_user.id,encode(extensions.digest(v_token,'sha256'),'hex'),v_exp);
  return query select v_token,v_user.account_key,v_user.display_name,v_user.phone,v_user.role,v_user.must_change_password,v_exp;
end $$;
grant execute on function public.app_login(text,text) to anon, authenticated;

create or replace function public.app_get_profile(p_token text)
returns table(account_key text,display_name text,phone text,role text,must_change_password boolean)
language plpgsql security definer set search_path=public
as $$
declare v_uid uuid;
begin
 select s.user_id into v_uid from public._app_session_user(p_token) s;
 if v_uid is null then raise exception 'Sesi login tidak valid atau sudah kedaluwarsa'; end if;
 update public.app_sessions set last_used_at=now() where token_hash=encode(extensions.digest(p_token,'sha256'),'hex');
 return query select u.account_key,u.display_name,u.phone,u.role,u.must_change_password from public.app_users u where u.id=v_uid;
end $$;
grant execute on function public.app_get_profile(text) to anon, authenticated;

create or replace function public.app_change_password(p_token text,p_old_password text,p_new_password text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_uid uuid; v_hash text;
begin
 if length(coalesce(p_new_password,''))<6 then raise exception 'Password baru minimal 6 karakter'; end if;
 select s.user_id into v_uid from public._app_session_user(p_token) s;
 if v_uid is null then raise exception 'Sesi login tidak valid'; end if;
 select password_hash into v_hash from public.app_users where id=v_uid;
 if v_hash<>extensions.crypt(p_old_password,v_hash) then raise exception 'Password lama salah'; end if;
 update public.app_users set password_hash=extensions.crypt(p_new_password,extensions.gen_salt('bf')),must_change_password=false,updated_at=now() where id=v_uid;
 delete from public.app_sessions where user_id=v_uid and token_hash<>encode(extensions.digest(p_token,'sha256'),'hex');
 return true;
end $$;
grant execute on function public.app_change_password(text,text,text) to anon, authenticated;

create or replace function public.app_upsert_visit(p_token text,p_visit jsonb)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_uid uuid; v_key text; v_role text; v_sales_email text;
begin
 select s.user_id,s.account_key,s.role into v_uid,v_key,v_role from public._app_session_user(p_token) s;
 if v_uid is null then raise exception 'Sesi login tidak valid'; end if;
 v_sales_email:=coalesce(p_visit->>'sales_email',v_key);
 if v_role<>'admin' and v_sales_email<>v_key then raise exception 'Tidak boleh menyimpan data sales lain'; end if;
 if v_role='admin' then select id into v_uid from public.app_users where account_key=v_sales_email and role='sales'; end if;
 if v_uid is null then raise exception 'Akun sales tidak ditemukan'; end if;
 insert into public.visits(id,user_id,sales_email,sales_name,customer_no,customer_code,customer_name,area,status,visit_type,check_in_at,check_out_at,updated_at,payload)
 values(p_visit->>'id',v_uid,v_sales_email,coalesce(p_visit->>'sales_name',''),coalesce(p_visit->>'customer_no',''),coalesce(p_visit->>'customer_code',''),coalesce(p_visit->>'customer_name',''),coalesce(p_visit->>'area',''),coalesce(p_visit->>'status',''),coalesce(p_visit->>'visit_type','Kunjungan Area'),nullif(p_visit->>'check_in_at','')::timestamptz,nullif(p_visit->>'check_out_at','')::timestamptz,coalesce(nullif(p_visit->>'updated_at','')::timestamptz,now()),coalesce(p_visit->'payload','{}'::jsonb))
 on conflict(id) do update set sales_name=excluded.sales_name,customer_no=excluded.customer_no,customer_code=excluded.customer_code,customer_name=excluded.customer_name,area=excluded.area,status=excluded.status,visit_type=excluded.visit_type,check_in_at=excluded.check_in_at,check_out_at=excluded.check_out_at,updated_at=excluded.updated_at,payload=excluded.payload;
 return true;
end $$;
grant execute on function public.app_upsert_visit(text,jsonb) to anon, authenticated;

create or replace function public.app_pull_visits(p_token text,p_limit integer default 5000)
returns table(id text,updated_at timestamptz,payload jsonb)
language plpgsql security definer set search_path=public
as $$
declare v_uid uuid; v_role text;
begin
 select s.user_id,s.role into v_uid,v_role from public._app_session_user(p_token) s;
 if v_uid is null then raise exception 'Sesi login tidak valid'; end if;
 if v_role='admin' then
  return query select v.id,v.updated_at,v.payload from public.visits v order by v.updated_at desc limit least(greatest(p_limit,1),10000);
 else
  return query select v.id,v.updated_at,v.payload from public.visits v where v.user_id=v_uid order by v.updated_at desc limit least(greatest(p_limit,1),10000);
 end if;
end $$;
grant execute on function public.app_pull_visits(text,integer) to anon, authenticated;

create or replace function public.app_admin_save_settings(p_token text,p_users jsonb,p_assignments jsonb)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_role text; r record;
begin
 select s.role into v_role from public._app_session_user(p_token) s;
 if v_role is distinct from 'admin' then raise exception 'Hanya admin yang dapat mengubah pengaturan'; end if;
 for r in select * from jsonb_to_recordset(coalesce(p_users,'[]'::jsonb)) as x(account_key text,display_name text,phone text,role text)
 loop
  update public.app_users set display_name=r.display_name,login_name=lower(trim(r.display_name)),phone=r.phone,updated_at=now() where account_key=r.account_key;
 end loop;
 delete from public.area_assignments;
 insert into public.area_assignments(sales_email,area)
 select x.sales_email,x.area from jsonb_to_recordset(coalesce(p_assignments,'[]'::jsonb)) as x(sales_email text,area text)
 on conflict do nothing;
 return true;
end $$;
grant execute on function public.app_admin_save_settings(text,jsonb,jsonb) to anon, authenticated;

create or replace function public.app_admin_reset_password(p_token text,p_account_key text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_role text; v_phone text; v_uid uuid;
begin
 select s.role into v_role from public._app_session_user(p_token) s;
 if v_role is distinct from 'admin' then raise exception 'Hanya admin yang dapat reset password'; end if;
 select id,phone into v_uid,v_phone from public.app_users where account_key=p_account_key;
 if v_uid is null then raise exception 'Akun tidak ditemukan'; end if;
 update public.app_users set password_hash=extensions.crypt(v_phone,extensions.gen_salt('bf')),must_change_password=true,updated_at=now() where id=v_uid;
 delete from public.app_sessions where user_id=v_uid;
 return true;
end $$;
grant execute on function public.app_admin_reset_password(text,text) to anon, authenticated;

-- Akun awal. Password awal = nomor handphone.
insert into public.app_users(account_key,login_name,display_name,phone,password_hash,role,must_change_password)
values
 ('rini@rml.app','rini','Rini','085668027045',extensions.crypt('085668027045',extensions.gen_salt('bf')),'sales',true),
 ('lisna@rml.app','lisna','Lisna','085218600582',extensions.crypt('085218600582',extensions.gen_salt('bf')),'sales',true),
 ('septino@rml.app','septino','Septino','08116946999',extensions.crypt('08116946999',extensions.gen_salt('bf')),'sales',true),
 ('admin@rml.app','admin','Admin','082284879722',extensions.crypt('082284879722',extensions.gen_salt('bf')),'admin',true)
on conflict(account_key) do update set login_name=excluded.login_name,display_name=excluded.display_name,phone=excluded.phone,role=excluded.role;

update public.app_users set can_switch_area_freely=true where account_key='septino@rml.app';

-- Verifikasi: hasil harus menampilkan 4 akun.
select account_key,login_name,display_name,phone,role,must_change_password from public.app_users order by role,display_name;
